// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDspX14cjp61izHTel47b2BDSjsHy6FUHI',
    appId: '1:1028464680190:web:c9bd48a85d478191ac99af',
    messagingSenderId: '1028464680190',
    projectId: 'signlanguage-2cf1e',
    authDomain: 'signlanguage-2cf1e.firebaseapp.com',
    databaseURL: 'https://signlanguage-2cf1e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signlanguage-2cf1e.appspot.com',
    measurementId: 'G-YQS5E49RL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBthOyMMP6Qkr6T2bnJE4STc6q2rRBesaY',
    appId: '1:1028464680190:android:006757707ec40661ac99af',
    messagingSenderId: '1028464680190',
    projectId: 'signlanguage-2cf1e',
    databaseURL: 'https://signlanguage-2cf1e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signlanguage-2cf1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwaKjw12zBUFzxdxqJKTnqplH84_My_18',
    appId: '1:1028464680190:ios:9ee6e78d9ed9033fac99af',
    messagingSenderId: '1028464680190',
    projectId: 'signlanguage-2cf1e',
    databaseURL: 'https://signlanguage-2cf1e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signlanguage-2cf1e.appspot.com',
    iosBundleId: 'com.example.videoStreamClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwaKjw12zBUFzxdxqJKTnqplH84_My_18',
    appId: '1:1028464680190:ios:9ee6e78d9ed9033fac99af',
    messagingSenderId: '1028464680190',
    projectId: 'signlanguage-2cf1e',
    databaseURL: 'https://signlanguage-2cf1e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signlanguage-2cf1e.appspot.com',
    iosBundleId: 'com.example.videoStreamClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDspX14cjp61izHTel47b2BDSjsHy6FUHI',
    appId: '1:1028464680190:web:8cc79ee3f4b047c1ac99af',
    messagingSenderId: '1028464680190',
    projectId: 'signlanguage-2cf1e',
    authDomain: 'signlanguage-2cf1e.firebaseapp.com',
    databaseURL: 'https://signlanguage-2cf1e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signlanguage-2cf1e.appspot.com',
    measurementId: 'G-GWN6PXF872',
  );
}
